# Generated by Django 3.2.16 on 2022-11-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemodel',
            old_name='unique_id',
            new_name='license_number',
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='license_state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
