# Generated by Django 4.0.8 on 2022-11-09 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_standardpage_cta'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceindexpage',
            name='cta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.homectasection'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='cta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.homectasection'),
        ),
    ]
