# Generated by Django 4.0.8 on 2022-11-10 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_serviceindexpage_cta_servicepage_cta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(help_text='cta text', verbose_name='description')),
                ('step_info_one', models.CharField(blank=True, max_length=50, null=True, verbose_name='step_info_one')),
                ('step_info_two', models.CharField(blank=True, max_length=255, null=True, verbose_name='step_info_two')),
            ],
            options={
                'verbose_name': 'service_step',
                'verbose_name_plural': 'service_step_list',
            },
        ),
        migrations.AddField(
            model_name='servicepage',
            name='step_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_one', to='service.servicestep'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='step_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_three', to='service.servicestep'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='step_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_two', to='service.servicestep'),
        ),
    ]
