# Generated by Django 3.2.15 on 2022-09-06 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsortiumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(auto_now_add=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('consortium_type', models.CharField(blank=True, choices=[('bs', 'bronze'), ('sl', 'silver'), ('gd', 'gold')], default='bs', max_length=3, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.usercompanymodel')),
            ],
        ),
        migrations.CreateModel(
            name='ConsortiumPurchaseCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_action', models.DateTimeField(auto_now_add=True)),
                ('consortium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consortium.consortiummodel')),
            ],
        ),
    ]
