# Generated by Django 4.0.8 on 2022-11-05 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('dot_number', models.CharField(blank=True, max_length=30, null=True)),
                ('account_type', models.CharField(choices=[('NC', 'NOT COMPANY'), ('TC', 'TRUCKING'), ('HH', 'HOME HEALTH'), ('AG', 'AGENCY')], max_length=5)),
                ('add_date', models.DateField(auto_now_add=True)),
                ('quest_client_id', models.CharField(blank=True, max_length=30, null=True)),
                ('consortium_purchased', models.BooleanField(default=False)),
                ('is_company_true', models.BooleanField(default=False, null=True)),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['add_date'],
            },
        ),
    ]
