# Generated by Django 3.2.16 on 2022-11-14 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_get_info', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('quest_id', models.CharField(blank=True, max_length=30, null=True)),
                ('quest_reference_id', models.CharField(blank=True, max_length=30, null=True)),
                ('client_id', models.CharField(blank=True, max_length=30, null=True)),
                ('extra', models.CharField(blank=True, max_length=300, null=True)),
                ('stage', models.CharField(blank=True, choices=[('CT', 'CREATED'), ('ST', 'STARTED'), ('AC', 'API CALL SENT'), ('AR', 'API CALL RESPONSE'), ('AE', 'API CALL BAD'), ('SU', 'ALL STATUS SENT')], max_length=3, null=True)),
                ('last_call_key', models.CharField(blank=True, max_length=255, null=True)),
                ('get_info_key', models.CharField(blank=True, max_length=255, null=True)),
                ('get_info_json', models.JSONField(blank=True, null=True)),
                ('get_info_error_message', models.JSONField(blank=True, null=True)),
                ('get_info_pass', models.BooleanField(default=False)),
                ('step_complete', models.BooleanField(default=False)),
                ('error_occured', models.BooleanField(default=False)),
                ('error_message', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrugTestOrderFail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drugtest.questordermodel')),
                ('user_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.usercompanymodel')),
            ],
        ),
        migrations.CreateModel(
            name='DrugTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_order', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.usercompanymodel')),
                ('order_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drugtest.questordermodel')),
            ],
        ),
    ]
