# Generated by Django 3.2.16 on 2022-11-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugtest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questordermodel',
            name='from_order',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
