# Generated by Django 4.0.8 on 2022-11-09 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('base', '0002_remove_homepage_cta_1_homectaonerelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='button_one_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='button_one_link'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='button_one_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='button_one_text'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='button_two_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='button_two_link'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='button_two_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='button_two_text'),
        ),
        migrations.AddField(
            model_name='homectasection',
            name='background_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homectasection',
            name='button_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='button_link'),
        ),
        migrations.AddField(
            model_name='homectasection',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='button_text'),
        ),
    ]
