# Generated by Django 4.0.8 on 2022-11-10 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_standardpage_cta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='cta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standard_cta', to='base.homectasection'),
        ),
    ]
